liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        thumb48:
            quality: 75
            filters:
                thumbnail: { size: [48, 48], mode: outbound }
        thumb300:
            quality: 75
            filters:
                thumbnail: { size: [300, 300], mode: outbound }
